default: &default
  adapter: mysql2
  pool: 25
  timeout: 5000
  username: root
  password:
  encoding: utf8
  host: localhost

test:
  <<: *default
  database: trestor_test

development:
  <<: *default
  database: trestor_development

production:
  <<: *default
  database: trestor_development
