# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f68e0ce530356f94475287e56e479cf5a4c81bf2fc684b43f635cfc8b917dd6915c450866b6d7a812e845d062e2a200eed2741c032336d3dcc7c20874148012

test:
  secret_key_base: c6dd1b9de46f7bbd1bb4b13676e1cc14b1cd85c49febe0d606ff544121c00440a08fbbb8f69f2afdaf7c0cce3999db64130f7da77a977bc9ee10bf04f3cdf783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
